---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:      aws
  namespace: default

spec:
  storageClassName: aws
  volumeMode:       Filesystem
  accessModes:     [ReadWriteOnce]
  resources:
    requests:
      storage: 2Gi
