---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: aws
  annotations:
    storageclass.kubernetes.io/is-default-class:   "true"
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/aws-ebs

provisioner:       kubernetes.io/aws-ebs
reclaimPolicy:     Delete
volumeBindingMode: Immediate

parameters:
  type: gp2
