name: hugernetes

instance_groups:
  - name:      etcd
    instances: 3
    azs:       [z1,z2,z3]
    vm_resources:
      cpu: 2
      ram: 2048
      ephemeral_disk_size: 20_000
    persistent_disk: 20_000

    stemcell:  default

    networks:
      - name: default

    jobs:
      - name: etcd
        release: k8s

  - name:      control
    instances: 3
    azs:       [z1,z2,z3]
    vm_type:   large
    stemcell:  default

    persistent_disk_type: default

    networks:
      - name: default

    jobs:
      - name: control
        release: k8s
        properties:
          apiserver:
            additional-sans:
              - 10.128.23.1
          cluster:
            name: hugernetes
            dns:  10.128.23.2
          networks:
            nodes:    10.128.16.0/24
            services: 10.128.23.0/24
            pods:     10.128.32.0/21
          encryption:
            key: ((encryption-key))
          tls:
            ca:
              certificate: ((tls-ca.certificate))
              key:         ((tls-ca.private_key))
            sa:
              certificate: ((tls-sa.certificate))
              key:         ((tls-sa.private_key))

      - name: jumpbox
        release: k8s
      - name: smoke-tests
        release: k8s

  - name:      node
    instances: 5
    azs:       [z1,z2,z3]
    vm_type:   large
    stemcell:  default

    persistent_disk_type: default

    networks:
      - name: default

    jobs:
      - name: runtime-runc
        release: k8s
        properties:
          cni: flannel
      - name: net-flannel
        release: k8s
      - name: kubelet
        release: k8s

      - name: nfs
        release: k8s

variables:
  - name: tls-ca
    type: certificate
    options:
      is_ca: yes
      common_name: ca

  - name: tls-sa
    type: certificate
    options:
      is_ca: yes
      common_name: sa

  - name: encryption-key
    type: password
    options:
      length: 32
      include_special: yes

update:
  canaries: 1
  max_in_flight: 1
  serial: true
  canary_watch_time: 1000-120000
  update_watch_time: 1000-120000

stemcells:
  - alias:   default
    os:      ubuntu-xenial
    version: latest

releases:
  - name:    k8s
    version: latest
