name: labernetes

instance_groups:
  - name:      k8s
    instances: 3
    azs:       [z1,z2,z3]
    azs: [z1]
    vm_resources:
      cpu: 2
      ram: 2048
      ephemeral_disk_size: 20_000
    persistent_disk: 20_000

    stemcell:  default

    networks:
      - name: default

    jobs:
      - name: etcd
        release: k8s
      - name: control
        release: k8s
        properties:
          apiserver:
            flags:
              - audit-log-maxage: 5
            additional-sans:
              - 10.128.18.1
            audit-policy:
              apiVersion: audit.k8s.io/v1
              kind: Policy
              rules:
                - level: Request
          cluster:
            name: labernetes
            dns:  10.128.20.1
          networks:
            pods:     10.128.19.0/24
            services: 10.128.20.0/24
            nodes:    10.128.21.0/24
          encryption:
            key: ((encryption-key))
          tls:
            ca:
              certificate: ((tls-ca.certificate))
              key:         ((tls-ca.private_key))
            sa:
              certificate: ((tls-sa.certificate))
              key:         ((tls-sa.private_key))

      - name: lb
        release: k8s
        properties:
          port: 443
          autoconfigure: static
          backend:
            ips:
              - 10.128.16.131
              - 10.128.16.132
              - 10.128.16.133
            port: 6443

      - name: runtime-runc
        release: k8s
      - name: kubelet
        release: k8s
      - name: nfs
        release: k8s

      - name: jumpbox
        release: k8s
      - name: smoke-tests
        release: k8s

variables:
  - name: tls-ca
    type: certificate
    options:
      is_ca: yes
      common_name: ca

  - name: tls-sa
    type: certificate
    options:
      is_ca: yes
      common_name: sa

  - name: encryption-key
    type: password
    options:
      length: 32
      include_special: yes

update:
  canaries: 1
  max_in_flight: 1
  serial: true
  canary_watch_time: 1000-120000
  update_watch_time: 1000-120000

stemcells:
  - alias:   default
    os:      ubuntu-xenial
    version: latest

releases:
  - name:    k8s
    version: latest
