name: prodernetes

instance_groups:
  - name:      lb
    instances: 2
    azs:       [z1,z2,z3]
    azs: [z1]
    vm_resources:
      cpu: 2
      ram: 2048
      ephemeral_disk_size: 2048
    stemcell: default
    networks:
      - name: default

    jobs:
      - name: lb
        release: k8s
        properties:
          vrrp:
            id: 240
            ip: 10.128.16.240

  - name:      control
    instances: 3
    azs:       [z1,z2,z3]
    azs: [z1]
    vm_resources:
      cpu: 2
      ram: 2048
      ephemeral_disk_size: 20_000
    persistent_disk: 20_000
    stemcell:  default
    networks:
      - name: default

    jobs:
      - name: etcd
        release: k8s
      - name: control
        release: k8s
        properties:
          kubelet:
            instance-groups:
              - node.default
              - control.default
          apiserver:
            additional-sans:
              - 10.128.22.1
              - 10.128.16.240
          cluster:
            name: prodernetes
            dns:  10.128.22.2
          networks:
            nodes:    10.128.16.0/24
            services: 10.128.22.0/24
            pods:     10.128.24.0/21
          encryption:
            key: ((encryption-key))
          tls:
            ca:
              certificate: ((tls-ca.certificate))
              key:         ((tls-ca.private_key))
            sa:
              certificate: ((tls-sa.certificate))
              key:         ((tls-sa.private_key))
      - name: net-flannel
        release: k8s
      - name: runtime-runc
        release: k8s
        properties:
          cni: flannel
      - name: kubelet
        release: k8s
        properties:
          apiserver: 10.128.16.240
          master: true

      - name: jumpbox
        release: k8s
      - name: smoke-tests
        release: k8s

  - name:      node
    instances: 5
    azs:       [z1,z2,z3]
    azs: [z1]
    vm_resources:
      cpu: 2
      ram: 2048
      ephemeral_disk_size: 20_000
    persistent_disk: 20_000
    stemcell:  default
    networks:
      - name: default

    jobs:
      - name: net-flannel
        release: k8s
      - name: runtime-runc
        release: k8s
        properties:
          cni: flannel
      - name: kubelet
        release: k8s
        properties:
          apiserver: 10.128.16.240
      - name: nfs
        release: k8s

variables:
  - name: tls-ca
    type: certificate
    options:
      is_ca: yes
      common_name: ca

  - name: tls-sa
    type: certificate
    options:
      is_ca: yes
      common_name: sa

  - name: encryption-key
    type: password
    options:
      length: 32
      include_special: yes

update:
  canaries: 1
  max_in_flight: 1
  serial: true
  canary_watch_time: 1000-120000
  update_watch_time: 1000-120000

stemcells:
  - alias:   default
    os:      ubuntu-xenial
    version: latest

releases:
  - name:    k8s
    version: latest
